# Generated by Django 2.2.2 on 2019-10-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='hallTicketNumber',
        ),
    ]
