# Generated by Django 2.2.2 on 2019-10-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20191016_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='sem1Completed',
            field=models.CharField(choices=[('completed', 'completed'), ('stillBacklog', 'stillBacklog')], default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sem2Completed',
            field=models.CharField(choices=[('completed', 'completed'), ('stillBacklog', 'stillBacklog')], default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sem3Completed',
            field=models.CharField(choices=[('completed', 'completed'), ('stillBacklog', 'stillBacklog')], default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sem4Completed',
            field=models.CharField(choices=[('completed', 'completed'), ('stillBacklog', 'stillBacklog')], default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sem5Completed',
            field=models.CharField(choices=[('completed', 'completed'), ('stillBacklog', 'stillBacklog')], default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sem6Completed',
            field=models.CharField(choices=[('completed', 'completed'), ('stillBacklog', 'stillBacklog')], default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sem7Completed',
            field=models.CharField(choices=[('completed', 'completed'), ('stillBacklog', 'stillBacklog')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sem8Completed',
            field=models.CharField(choices=[('completed', 'completed'), ('stillBacklog', 'stillBacklog')], default='No', max_length=3),
        ),
    ]
