# Generated by Django 2.2.2 on 2019-10-18 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_certificates_certificatedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='student.StudentProfile'),
        ),
        migrations.CreateModel(
            name='Placed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('payPackage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.DateTimeField(default=2019)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='student.StudentProfile')),
            ],
        ),
    ]
