# Generated by Django 2.2.2 on 2019-10-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20191018_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='sem1Completed',
            field=models.CharField(choices=[('completed', 'completed'), ('stillBacklog', 'stillBacklog')], default='Yes', max_length=7),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sem2Completed',
            field=models.CharField(choices=[('completed', 'completed'), ('stillBacklog', 'stillBacklog')], default='Yes', max_length=7),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sem3Completed',
            field=models.CharField(choices=[('completed', 'completed'), ('stillBacklog', 'stillBacklog')], default='Yes', max_length=7),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sem4Completed',
            field=models.CharField(choices=[('completed', 'completed'), ('stillBacklog', 'stillBacklog')], default='Yes', max_length=7),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sem5Completed',
            field=models.CharField(choices=[('completed', 'completed'), ('stillBacklog', 'stillBacklog')], default='Yes', max_length=7),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sem6Completed',
            field=models.CharField(choices=[('completed', 'completed'), ('stillBacklog', 'stillBacklog')], default='Yes', max_length=7),
        ),
    ]
