# Generated by Django 2.2.2 on 2019-10-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('companyEmail', models.CharField(max_length=50)),
                ('exam_date', models.DateField()),
                ('eligibleStudents', models.FileField(upload_to='')),
            ],
        ),
    ]
