# Generated by Django 2.2.2 on 2019-10-30 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20191030_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='date',
            field=models.DateField(default=datetime.date(2019, 10, 30)),
        ),
    ]
